### ISSUE TITLE
[Question] How can I pass argument to the parent command

### ISSUE THREAD

**Issue by upatelte** [anand1st/sshd-shell-spring-boot#16]
I noticed that you can pass argument to the subcommand, but i wanted to pass the argument to the parent command (the command does not have any sub commands).

I understand the issue behind implementing this, since the code will have to distinguish between subcommand and argument. However, just wondering if there is a workaround.

**Comment by anand1st** [comment]
At the moment, your requirement is not supported and there's no workaround. However, it might be possible to distinguish subcommand and argument by using the following logic.  First, check if argument is part of the subcommands collection. If no, treat it as an argument. Otherwise, treat it as a subcommand. However, this would require some code change. Will add this change in the next release.
